name = "personal-drive-img"
pages_build_output_dir = "public"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGINS = "davflare-8fq.pages.dev"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "personal-drive-images"
